### ISSUE TITLE
TcpStream::try_clone() is deprecated

### ISSUE THREAD

**Issue by ekse** [Devolutions/cowrpc-rs#2]
TcpStream::try_clone() was deprecated as it is bug-prone, calling this function on the latest release returns an Error. As a temporary fix, we should set the tokio-tcp dependency to 0.1.2 with `tokio-tcp = "=0.1.2"`

https://github.com/tokio-rs/tokio/pull/824

**Comment by CBenoit** [comment]
This is addressed by our last tokio update.
